<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Som</string>
    <key>nameName</key>
    <string>source.som</string>
    <key>fileTypes</key>
    <array>
      <string>som</string>
    </array>
    <key>firstLineMatch</key>
    <string>^#!/.*\bsom\b</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#expression</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#invalid</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>expression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#special</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operator</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keyword</string>
          </dict>
        </array>
      </dict>
      <key>special</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>true|false</string>
            <key>name</key>
            <string>constant.language.boolean.som</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\(\)</string>
            <key>name</key>
            <string>constant.language.null.som</string>
          </dict>
        </array>
      </dict>
      <key>number</key>
      <dict>
        <key>match</key>
        <string>\b\b[0-9]+(?:\.[0-9]*)?\b|\b0b[0-1]+\b|\b0c[0-7]+\b|\b0x[0-9a-fA-F]+\b\b</string>
        <key>name</key>
        <string>constant.numeric.som</string>
      </dict>
      <key>operator</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>&lt;&lt;|&gt;&gt;</string>
            <key>name</key>
            <string>keyword.operator.bitwise.shift.som</string>
          </dict>
          <dict>
            <key>match</key>
            <string>==|/=</string>
            <key>name</key>
            <string>keyword.operator.comparison.som</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&lt;=|&gt;=|&lt;&gt;|&lt;|&gt;</string>
            <key>name</key>
            <string>keyword.operator.relational.som</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\!|&amp;&amp;|\|\||\^\^</string>
            <key>name</key>
            <string>keyword.operator.logical.som</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\&amp;|\^|\|</string>
            <key>name</key>
            <string>keyword.operator.bitwise.som</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\*|/|-|\+|\%</string>
            <key>name</key>
            <string>keyword.operator.arithmetic.som</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.\.</string>
            <key>name</key>
            <string>punctuation.definition.range.som</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\.</string>
            <key>name</key>
            <string>punctuation.accessor.dot.som</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\,</string>
            <key>name</key>
            <string>punctuation.separator.sequence.som</string>
          </dict>
        </array>
      </dict>
      <key>keyword</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\?\?</string>
            <key>name</key>
            <string>keyword.control.conditional.switch.som</string>
          </dict>
          <dict>
            <key>match</key>
            <string>=&gt;</string>
            <key>name</key>
            <string>keyword.control.conditional.switch.som</string>
          </dict>
          <dict>
            <key>match</key>
            <string>=&gt;</string>
            <key>name</key>
            <string>keyword.control.loop.for.som</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\?</string>
            <key>name</key>
            <string>keyword.control.conditional.if.som</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;!:):(?!:)</string>
            <key>name</key>
            <string>keyword.control.conditional.else.som</string>
          </dict>
        </array>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.som</string>
            <key>begin</key>
            <string>---</string>
            <key>end</key>
            <string>---</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.line.som</string>
            <key>match</key>
            <string>--.*$</string>
          </dict>
        </array>
      </dict>
      <key>string_escaped_char</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.som</string>
            <key>match</key>
            <string>\\(a|b|e|f|n|r|t|v|\\|'|"|0)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>invalid.illegal.unknown-escape.som</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
        </array>
      </dict>
      <key>string_placeholder</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.other.placeholder.som</string>
            <key>match</key>
            <string>(?x)%
  (\d+\$)?                                      # field (argument #)
  [#0\- +']*                                    # flags
  [,;:_]?                                       # separator character (AltiVec)
  ((-?\d+)|\*(-?\d+\$)?)?                       # minimum field width
  (\.((-?\d+)|\*(-?\d+\$)?)?)?                  # precision
  (hh|h|ll|l|j|t|z|q|L|vh|vl|v|hv|hl)?          # length modifier
  (\[[^\]]+\]|[am]s|[diouxXDOUeEfFgGaACcSspn%]) # conversion type</string>
          </dict>
          <dict>
            <key>name</key>
            <string>invalid.illegal.placeholder.som</string>
            <key>match</key>
            <string>(%)(?!"\s*(PRI|SCN))</string>
          </dict>
        </array>
      </dict>
      <key>invalid</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\s+</string>
          </dict>
          <dict>
            <key>name</key>
            <string>invalid.illegal.som</string>
            <key>match</key>
            <string>\S</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>