// File generated by somc, see https://github.com/SjVer/Som-Lang
#include <som/value.h>

// function `+/1`
value $2b$2f1 (value parg$2f3, value parg$2f2) {
  return Unboxed_val(Val_value(parg$2f3) + Val_value(parg$2f2)); 
}

// function `foo/4`
value foo$2f4 (value x$2f5, value y$2f6) {
  return $2b$2f1 (x$2f5, y$2f6); 
}

// global `two/7`
value two$2f7 () {
  return Unboxed_val(2); 
}

// global `main/8`
value main$2f8 () {
  return foo$2f4 (two$2f7(), Unboxed_val(3)); 
}

value (*som_entrypoint)(value) = &main$2f8;
